# Generated by Django 3.1 on 2020-08-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_plan_ID',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_price_ID',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
