# Generated by Django 3.1 on 2020-08-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0005_category_clicks'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='history',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='history',
            field=models.ManyToManyField(to='library.Video'),
        ),
    ]
